# Generated by Django 3.2 on 2021-04-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_creator', models.CharField(max_length=200)),
                ('creator_email', models.CharField(max_length=200)),
                ('task_text', models.CharField(max_length=200)),
                ('task_status', models.IntegerField(choices=[('задача не выполнена', 0), ('задача не выполнена, отредактирована админом', 1), ('задача выполнена', 10), ('задача отредактирована админом и выполнена', 11)], default=0)),
            ],
        ),
    ]
