# Generated by Django 3.2 on 2021-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(0, 'задача не выполнена'), (1, 'задача не выполнена, отредактирована админом'), (10, 'задача выполнена'), (11, 'задача отредактирована админом и выполнена')], default=0),
        ),
    ]
