# Generated by Django 3.2 on 2021-04-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20210424_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creator_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_creator',
            new_name='username',
        ),
    ]
